### ISSUE TITLE
Handling missing data

### ISSUE THREAD

**Issue by basille** [mablab/sftraj#5]
Missing data can be anything: geographic coordinates (e.g. failed attempt at getting a GPS fix), time coordinate, ancillary data.

**Comment by basille** [comment]
**From Ioannis Kosmidis**

The tracking devices athletes use typically return the following variables (see also Section 3 of the vignette of `trackeR`):

1. time
2. latitude
3. longitude
4. altitude
5. distance
6. heart_rate
7. speed
8. cadence_running
9. cadence_cycling
10. power
11. temperature

The pain with athlete trajectories is that any of the above information can be missing, including the timestamp (and there I made the assumption that at least the order of the observations in the container file are correct).

The "cleaning" involves operations that allow the user to infer variables from others. There reason we allow this is that the data can miss some of the variables above (including time!) either by choices of the athlete, particular training conditions, or because the device did not do its job properly (e.g. because its data-recording procedures adapted to clogged memory or low battery conditions). Frequent examples we encounter are:
  - have time, lat, lon, speed only (so we can infer distance either by lat, lon or speed)
  - have time, lat, lon, distance only (so we can infer speed etc)
  - have time, distance only (so we can infer speed)
  - have time, lat lon, speed, altitude (so we can infer distance)
and so on.

**Comment by edzer** [comment]
FYI: `NA` values are not allowed in simple feature geometries; a grey zone is `NA` values in `POINT` geometries, which is taken as a `POINT EMPTY` (though of as: "no point for which...").

**Comment by basille** [comment]
Oh. That will have to be really accounted for. I guess we're in for more testing…

Is this set in stone, or could empty `LINESTRING`s be considered too? (I think PostGIS handles `NULL` geometries, whatever they are, right? Isn't this part of the SF standard?)

**Comment by edzer** [comment]
`LINESTRING EMPTY`s are in R represented by linestrings with zero points. I don't think the simple feature model caters for geometries with NA coordinates. You can of course start representing them, but all of GEOS/GDAL/liblwgeom might break on it.

**Comment by basille** [comment]
That might be enough! If we stick to steps, we would need empty steps — `LINESTRING` with 0 points is good here. I guess not having NA coordinates in `LINESTRING`s is manageable: at the step level, this does not make sense to have NAs, and at a higher level of nesting, we can simply skip it (i.e. connecting existing points) or break the `LINESTRING` into `MULTILINESTRING`, depending on what is the goal.

The main issue will be handling sequences of "NA-point-NA", which is not enough to form a step. In this case, we should have three empty steps, but that means we're potentially losing the intermediate point if we convert back to points.

**Comment by birderboone** [comment]
I'm tagging this to make sure it ends up on the issue page. I'm not sure if this is properly a use-case or just a discussion issue, but the discussion should be moved to the main sftraj repository one way or another. Any preference?

**Comment by basille** [comment]
We should definitely link to specific use cases. I can see at least two relevant examples:

* Workflow from raw data to `sftraj` objects (raw data should list failed GPS attempts);
* Interpolating missing locations, which necessarily mean missing locations are indicated in the `sftraj` object to start with.
